[[main]]
  name = "About Us"
  weight = 1

[[main]]
  name = "Our Story"
  url = "/about/"
  parent = "About Us"
  weight = 1

[[main]]
  name = "Join Us"
  url = "/join-us/"
  parent = "About Us"
  weight = 2

[[main]]
  name = "Collaborations"
  url = "/collaborations/"
  parent = "About Us"
  weight = 3

[[main]]
  name = "Creations"
  weight = 2

[[main]]
  name = "Dear Yesterday"
  url = "/creations/dear-yesterday/"
  parent = "Creations"
  weight = 1

[[main]]
  name = "Press Kit"
  url = "/press-kit/"
  parent = "Creations"
  weight = 2

[[main]]
  name = "Devlog"
  url = "/devlog/"
  weight = 3

[[main]]
  name = "Dev Log 1: Introduction"
  url = "/devlog/devlog-1-introduction/"
  parent = "Devlog"
  weight = 1

[[main]]
  name = "Dev Log 2: Trotson Radio"
  url = "/devlog/devlog-2-trotson-radio/"
  parent = "Devlog"
  weight = 2

[[main]]
  name = "Dev Log 3: Narrative Design"
  url = "/devlog/devlog-3-narrative-design/"
  parent = "Devlog"
  weight = 3

[[main]]
  name = "Dev Log 4"
  url = "/devlog/devlog-4/"
  parent = "Devlog"
  weight = 4

[[main]]
  name = "Dev Log 5"
  url = "/devlog/devlog-5/"
  parent = "Devlog"
  weight = 5

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 4

[[main]]
  name = "Instagram"
  parent = "Contact"
  pre = "instagram"
  url = "https://www.instagram.com/rustlingleavesgames/"

[[main]]
  name = "Facebook"
  parent = "Contact"
  pre = "facebook"
  url = "https://www.facebook.com/people/Rustling-Leaves-Games/61583138965806/"

[[main]]
  name = "LinkedIn"
  parent = "Contact"
  pre = "linkedin"
  url = "https://www.linkedin.com/company/rustling-leaves-games/posts/?feedView=all"

[[main]]
  name = "Twitch"
  parent = "Contact"
  pre = "twitch"
  url = "https://www.twitch.tv/rustling_leaves_games"

[[main]]
  name = "YouTube"
  parent = "Contact"
  pre = "youtube"
  url = "https://www.youtube.com/@RustlingLeavesGames"

[[main]]
  name = "Email"
  parent = "Contact"
  pre = "email"
  url = "mailto://hello@rustlingleavesgames.com"





[[footer]]
  name = "Instagram"
  pre = "instagram"
  url = "https://www.instagram.com/rustlingleavesgames/"

[[footer]]
  name = "Facebook"
  pre = "facebook"
  url = "https://www.facebook.com/people/Rustling-Leaves-Games/61583138965806/"

[[footer]]
  name = "LinkedIn"
  pre = "linkedin"
  url = "https://www.linkedin.com/company/rustling-leaves-games/posts/?feedView=all"

[[footer]]
  name = "Twitch"
  pre = "twitch"
  url = "https://www.twitch.tv/rustling_leaves_games"

[[footer]]
  name = "YouTube"
  pre = "youtube"
  url = "https://www.youtube.com/@RustlingLeavesGames"

[[footer]]
  name = "Email"
  pre = "email"
  url = "mailto://hello@rustlingleavesgames.com"

[[legal]]
  name = "Intellectual Property Protection"
  url = "/ip-and-rights/"
